name: Docs

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        
      - name: Install doxygen
        run: winget install --accept-source-agreements --accept-package-agreements -e --id DimitriVanHeesch.Doxygen

      - name: Run doxygen
        run: 'C:\Program` Files\doxygen\bin\doxygen.exe'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
